# Generated by Django 3.1.5 on 2021-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BolgPost',
            new_name='BlogPost',
        ),
    ]
